General_cells:
    parent_type: NULL 
    cell_proportion: NULL 
    rna_per_cell: NULL 
    model: NULL 
    genes: []
  
  Immune_general:
    parent_type: General_cells
    cell_proportion: 0.16
    rna_per_cell: NULL 
    model: explicit
    genes: [ADAP2, ADGRE3, ADGRG3, ADORA3, AIF1, AOAH, APOBEC3D, ARHGAP15, ARHGAP30, ARHGAP9, ARHGDIB, BANK1, BLK, C1QA, C1QC, C3AR1, C5AR1, CAMK4, 
            CBLB, CCDC69, CCL5, CCL7, CCR1, CCR2, CCR3, CD14, CD160, CD163, CD19, CD1D, CD2, CD22, CD226, CD244, CD247, CD27, 
            CD300A, CD300C, CD300E, CD300LB, CD302, CD33, CD37, CD3D, CD3E, CD3G, CD4, CD48, CD5, CD53, CD6, CD68, CD69, CD7, 
            CD79A, CD79B, CD86, CEACAM8, CECR1, CELF2, CLDND2, CLEC17A, CLEC2D, CLEC5A, CLEC7A, CMKLR1, CORO1A, CPNE5, CR2, CSF1R, CSF2RA, CSF3R, 
            CTSS, CTSW, CXCR1, CXCR2, CXCR5, CYBB, CYFIP2, CYTH4, CYTIP, DENND1C, DERL3, DOCK2, EAF2, ELF1, ELMO1, EVI2B, FAM129C, FAM78A, 
            FCER1G, FCGR1A, FCGR1B, FCGR2A, FCGR3B, FCMR, FCN1, FCRL1, FCRL2, FCRL3, FCRL5, FCRLA, FERMT3, FFAR2, FGR, FKBP11, FLT3LG, FMNL1, 
            FNBP1, FPR1, FPR2, FPR3, GLCCI1, GLT1D1, GPR174, GZMM, HCK, HCLS1, HLA-DOB, HMHA1, ICAM3, IFI30, IFITM2, IGFLR1, IGHG1, IGHG3, 
            IGHM, IGKC, IGLL5, IKZF1, IKZF3, IL10, IL16, IL2RB, IL2RG, IL4I1, INPP5D, IRF5, ITGAL, ITGAX, ITGB2, ITGB7, ITK, KCNA3, 
            KCNAB2, KCNJ15, KIR2DL1, KIR2DL2, KIR2DL3, KIR2DL4, KIR2DS2, KIR3DL1, KIR3DL2, KLRB1, KLRC2, KLRC3, KLRD1, KLRF1, KLRK1, LAG3, LAIR1, LAPTM5, 
            LAT, LAX1, LCK, LCP1, LIM2, LRRC25, LSP1, LTA, LY9, MAP4K1, MEFV, MMP25, MNDA, MRC1, MS4A1, MS4A4A, MS4A6A, MSR1, 
            MYO1F, MYO1G, MZB1, NCAM1, NCF2, NCKAP1L, NCR1, NCR3, NFATC2, NKG7, NLRC3, NMUR1, P2RY10, P2RY13, P2RY8, PADI2, PADI4, PARVG, 
            PAX5, PGLYRP1, PHOSPHO1, PIK3AP1, PILRA, PLA2G7, PLCB2, POU2AF1, PPP1R16B, PRF1, PRKCB, PTGDR, PTPN22, PTPN6, PTPRC, PTPRCAP, PVRIG, PYHIN1, 
            RAB7B, RAC2, RASGRP1, RASGRP2, RASGRP4, RASSF5, RCSD1, RHOH, RLTPR, S1PR5, SAMD3, SAMSN1, SASH3, SEC11C, SH2D1B, SIGLEC1, SIGLEC5, SIGLEC7, 
            SIGLEC9, SIRPB2, SIRPG, SIT1, SLA2, SLAMF6, SNX20, SP140, SPI1, SPIB, SPN, SSR4, STAP1, STAT5A, STK4, TAGAP, TBC1D10C, TBX21, 
            TCF7, TESPA1, TLR2, TMC8, TMIGD2, TNFAIP8, TNFAIP8L2, TNFRSF10C, TNFRSF13B, TNFRSF13C, TNFRSF17, TRAC, TRAF3IP3, TRAT1, TRBC2, TRDC, TREM2, TRGC1, 
            TRGC2, TXNDC11, TXNDC5, TYROBP, UBASH3A, VAV1, VNN2, VNN3, VPREB3, VSIG4, WAS, XCL2, ZBED2]
  
  Monocytes:
    parent_type: Monocytic_cells
    cell_proportion: 0.353983
    rna_per_cell: 0.5
    model: explicit
    genes: [AIFM3, AOAH, ARF6, ARG1, ASGR1, C9orf47, CCDC149, CCDC24, CCR1, CCR2, CD14, CD1D, CD207, CD300C, CD300E, CD300LB, CD302, CD33, 
            CECR1, CLEC4F, CNFN, CSF1R, CTSS, CYBB, EXOC8, FCN1, GBGT1, GOLPH3, IRF2BPL, IRF5, KCNE4, KCNJ10, KIAA1456, MEFV, MS4A6A, NT5DC4, 
            NTN3, OGG1, OLFML3, OLIG1, PADI4, PCBD1, PDE4DIP, RAB33B, RHOC, RXFP2, SCYL1, SDHD, SOCS7, SYT5, TBC1D2B, YIPF2, ZCCHC14, ZFYVE1, 
            ZNF521]
  
  B_cells:
  parent_type: Lymphoid_cells
  cell_proportion: 0.088496
  rna_per_cell: 1.0
  model: explicit
  genes: [ACTN2, ACTN4, ADAM28, ADGRE1, AIF1, ALOX5AP, AMICA1, AMN, ANKRD37, ANKRD55, ANXA1, AP2S1, ARHGAP25, ATP10A, B4GALT1, BANK1, BCL11A, BCL2, 
          BCL2L14, BEND4, BEX2, BHLHE40, BIVM, BLK, BLVRA, C1QC, C1orf186, C1orf54, C3orf14, CAMK1, CCDC152, CCDC8, CCL19, CCL3, CCR5, CCR7, 
          CD19, CD1A, CD1C, CD1D, CD2, CD207, CD22, CD27, CD28, CD33, CD3D, CD4, CD5, CD52, CD69, CD70, CD72, CD79A, 
          CD79B, CD80, CD82, CD83, CD86, CDK7, CDKN2AIP, CHN2, CHST10, CHURC1-FNTB, CLDND1, CLEC10A, CLEC4C, CLEC4F, CLECL1, CLIC3, CNR1, COA6, 
          COCH, COTL1, CPNE5, CPXM1, CR2, CRTAM, CRTC1, CSF1R, CTLA4, CTSH, CUEDC1, CXCL14, CXCR5, DAZL, DDIT4, DERL2, DERL3, DPPA4, 
          EAF2, ERCC1, EZR, FAM212A, FCER2, FCGR3A, FCRL1, FCRL2, FCRL5, FCRLA, FGD2, FHIT, FLT3LG, GALNT11, GNG5, GNG8, GNLY, GOLIM4, 
          GZMK, H3F3B, HEXB, HLA-DMA, HLA-DMB, HLA-DOA, HLA-DPA1, HLA-DPB1, HLA-DQB1, HLA-DRA, HLA-DRB1, ICOS, ICOSLG, ID2, IFNLR1, IGF1, IGHG1, IGHG3, 
          IGHM, IGKC, IGLL5, IL12A, IL27, IL32, IL3RA, IL5RA, IRF4, ITGAX, KCNK10, KIR2DL4, KLF4, KLRC3, KRT10, KRT5, LAIR1, LAMP1, 
          LAMTOR5, LCP2, LEPROTL1, LILRA4, LRRN3, LTA, MACROD2, MALT1, MAN1C1, MAP3K6, MGAT4A, MGST1, MPP6, MS4A1, MS4A7, MTHFD2, MYBPH, MYL6, 
          MZB1, NME1-NME2, NOSIP, NPM1, NR1H2, OAS2, PAX5, PCBD1, PDE4A, PDLIM1, PFDN1, PKP4, PLAC8, PLEKHB2, PLVAP, PNOC, POU2AF1, POU3F1, 
          PPFIBP2, PPIA, PRDM2, PRKAR2B, PRRG3, PRSS33, PSMB5, PTMA, PTP4A3, RASA4, RASA4B, RBM48, RGL1, RHOC, RNF130, RPL10, RPL18A, RPL21, 
          RPL22, RPL22L1, RPL23, RPL23A, RPL34, RPL39, RPL3L, RPL41, RPL7, RPLP1, RPS14, RPS18, RPS24, RPS27, RPS3, RPS6KA3, RPS6KA4, RPS6KA6, 
          S100A10, S1PR1, SCN3A, SEC11C, SIGLEC6, SIRPG, SIT1, SLAIN1, SLC35F3, SLC37A3, SLC39A6, SLC7A3, SMPD3, SNX2, SPN, SS18L2, SSPN, SSR4, 
          STAP1, STK33, STYK1, SUV420H1, SVIL, TBC1D4, TBPL2, TCEA3, TEX9, THBS4, TIAM1, TIMM13, TIMP1, TLE1, TMEM205, TMIGD2, TMSB10, TNF, 
          TNFAIP8L2, TNFRSF13B, TNFRSF13C, TNFRSF17, TNFRSF4, TNNT1, TPD52L2, TRAC, TRBV25-1, TTC39B, UBE2J1, VPREB3, VPS37C, VPS52, WLS, XCL2, XPNPEP1, YPEL5, 
          ZCCHC14, ZMAT4, ZNF22]

  NK_cells:
    parent_type: Immune_general
    cell_proportion: 0.070796
    rna_per_cell: 1.0
    model: explicit
    genes: [CD160, CD244, CD247, CD7, CLDND2, CTSW, GZMM, IL2RB, KIR2DL1, KIR2DL2,
            KIR2DL3, KIR2DL4, KIR2DS2, KIR3DL1, KIR3DL2, KLRB1, KLRC2, KLRC3, KLRD1, KLRF1,
            KLRK1, NCAM1, NCR1, NCR3, NKG7, NMUR1, PRF1, PTGDR, PYHIN1, S1PR5, SAMD3, SH2D1B,
            TMIGD2, XCL2, CCL5, LIM2]

  CD4_T_cells:
  parent_type: T_cells
  cell_proportion: 0.21238
  rna_per_cell: 1.0
  model: explicit
  genes: [ANKRD55, CCR4, CD2, CD27, CD28, CD3D, CD3E, CD3G, CD4, CD40LG, CD5, CD6, FHIT, FLT3LG, ICOS, IKZF1, IL2RA, IRF4, 
          ITK, LCK, LEF1, LTA, TESPA1, TNFRSF4, TRAC, TRAT1, TRBC2, UBASH3A]

  CD8_T_cells:
    parent_type: T_cells
    cell_proportion: 0.21238
    rna_per_cell: 1.0
    model: explicit
    genes: [CD2, CD3D, CD3G, CD3E, CD6, CD7, CD8A, CD8B, CD96, CRTAM, EOMES, FCRL6,
            FLT3LG, GZMA, GZMB, GZMH, GZMK, ITK, KLRC2, KLRC4, KLRK1, PRF1, PRKCQ, PTGDR,
            PVRIG, SH2D1A, TBX21, TCF7, THEMIS, TIGIT, TRAC, TRAT1, TRBC2, UBASH3A, XCL2,
            ZAP70, ZBED2, CCL5, CXCR3]

  Granulocytes:
    parent_type: Immune_general
    cell_proportion: 0.044248
    rna_per_cell: 2.7
    model: explicit
    genes: [ADGRE1, ADGRE3, ADGRG3, ADORA3, C5AR1, CCR3, CEACAM8, CLEC7A, CSF3R, CXCR1, CXCR2, EVI2B, FCGR2A, FCGR3B, FFAR2, FPR1, FPR2, GLT1D1, 
            GPR34, IFITM2, KCNJ15, LILRB3, MEFV, MMP25, MNDA, P2RY13, PADI2, PADI4, PGLYRP1, PHOSPHO1, RASGRP4, SIGLEC5, TNFRSF10C, VNN2, VNN3, WAS]

  Neutrophils:
    parent_type: Granulocytes
    cell_proportion: 0.024248
    rna_per_cell: 2.295
    model: explicit
    genes: [ADGRE1, B2M, BTK, C5AR1, CCR3, CD14, CD163, CSF3R, CTSS, CX3CR1, CXCR1, CXCR2, CYBB, EGR3, FCGR2A, FCGR3B, FFAR2, FPR1, 
            FPR2, GLT1D1, GPBAR1, HRH2, IFITM2, IL27, KCNJ15, MNDA, NFKBIZ, NLRP12, NOP10, PIM1, PRRG3, PRSS33, PTPN6, RASGRP4, RNASE2, S100A8, 
            S100A9, SH3BGRL, SIGLEC5, TNFAIP6, TNFAIP8L2, TNFRSF10C, TREM1, TULP2, VNN2, VNN3, WAS]

  Non_plasma_B_cells:
  parent_type: B_cells
  cell_proportion: 0.075222
  rna_per_cell: 1.0
  model: explicit
  genes: [ADAD2, ADAM19, ADAM28, ADIRF, AMY2A, ANKRD20A1, ANKRD37, ANXA1, AP2S1, AQP3, ATP10A, ATP6V1C2, AVPR1A, BACH2, BANK1, BCL11A, BCL2, BCL2L14, 
          BEND4, BLK, BLOC1S2, BLVRA, BTG4, BTNL9, C1orf186, C9orf135, C9orf47, CAMK4, CAPN12, CARD17, CASP3, CCDC152, CCL3, CCR2, CCR5, CCR7, 
          CCR9, CD19, CD1C, CD1D, CD2, CD200, CD207, CD22, CD27, CD37, CD3D, CD3E, CD4, CD48, CD5, CD52, CD69, CD70, 
          CD72, CD79A, CD79B, CD80, CD82, CD83, CD86, CDCA7L, CDKN2AIP, CDSN, CECR1, CEP295, CHN2, CIITA, CLEC10A, CLEC17A, CLEC4F, CLECL1, 
          CNR1, COCH, COMMD1, CPA5, CPNE5, CPXM1, CR2, CREBL2, CRTAM, CTLA4, CTSH, CXCR5, DDIT4, DERL2, DERL3, DPPA4, EAF2, EEF1A1, 
          ELL2, ENPP6, ENTPD1, EVI2B, EZH2, EZR, F13A1, FAM129C, FAM65A, FBXL16, FCER1A, FCER2, FCRL1, FCRL2, FCRL3, FCRL4, FCRL5, FCRLA, 
          FGFBP2, FHIT, FKBP11, FOLR2, FOXN3, GALNT11, GJA3, GLDC, GLYATL3, GNG8, GNLY, GOLPH3, GPLD1, GYPA, GZMK, H3F3B, HEBP2, HEXB, 
          HLA-DMA, HLA-DMB, HLA-DOA, HLA-DOB, HLA-DPA1, HLA-DPB1, HLA-DQA1, HLA-DQB1, HLA-DRA, HSH2D, ICOSLG, ID2, IGF1, IGHG1, IGHG3, IGHM, IGKC, IGLL5, 
          IKZF1, IL12A, IL22, IL27, IL32, IL3RA, IL7R, IRF4, ITGAX, KBTBD3, KCNH8, KCNQ3, KHNYN, KLRC3, KLRD1, KRT1, KRTAP10-10, LAIR1, 
          LAMTOR5, LBHD1, LEPROTL1, LIMS2, LST1, LTA, MACROD2, MALT1, MANF, MARCH3, MGAT3, MGST1, MPP6, MS4A1, MSN, MTHFD2, MTSS1, MYBPC2, 
          MYL6, MZB1, NME1-NME2, NR1H2, OR2M5, OR2T4, OR6A2, PASK, PAX5, PCBD1, PDE4A, PFDN5, PIK3R1, PKP4, PNOC, POU2AF1, PPFIBP2, PRDM1, 
          PRDM2, PRG3, PRR30, PRRG3, PSMB5, PTF1A, RAB13, RALGPS2, RAX, RBM48, RGL1, RHOC, RHOQ, RIC3, RNASEH2B, RNF130, RPL18A, RPL21, 
          RPL22L1, RPL23A, RPL26, RPL34, RPL36, RPL39L, RPL4, RPL41, RPL5, RPL6, RPL7A, RPLP0, RPS14, RPS18, RPS19, RPS20, RPS27, RPS27A, 
          RPS29, RPS6, RPS6KA3, RWDD2A, SCN3A, SEC11C, SIGLEC6, SIRPG, SIT1, SLAMF7, SLC17A9, SLC35E3, SLX1B, SMPD3, SMR3B, SNAP23, SNX2, SPIB, 
          SS18L2, SSPN, SSR4, STAP1, STYK1, TAAR2, TBC1D9, TCF7, TCL1A, TEX9, TFAP4, TIAF1, TIAM1, TIMP1, TLE1, TMEM182, TNF, TNFRSF13B, 
          TNFRSF13C, TNFRSF17, TOX2, TPT1, TRBC2, TRBV25-1, TSHZ2, TXNDC11, TXNDC5, UBE2J1, UBE2U, USP6NL, UXT, VASP, VPREB3, XCL2, YPEL5, ZMAT1, 
          ZMYND8]
  
  PDC:
  parent_type: Lymphoid_cells
  cell_proportion: 0.024248
  rna_per_cell: 0.147
  model: explicit
  genes: [ADAM28, ALOX5AP, BANK1, BCL11A, BLK, C1orf186, CCDC50, CCR2, CCR5, CD19, CD1C, CD22, CD36, CD37, CD4, CD72, CD79A, CD79B, 
          CIITA, CLEC17A, CLEC4C, CLIC3, CPEB3, DERL3, DPPA4, ERP29, FCER1A, FCRL5, FERMT3, GPM6B, HLA-DMA, HLA-DOA, HLA-DOB, HLA-DPB1, HLA-DQA1, HLA-DRA, 
          HLA-DRB1, HSH2D, ID2, IGHG3, IGHM, IGKC, IL3RA, IL5RA, IRF4, KCNK10, KLF11, KLF8, KRT5, LILRA4, MS4A1, MS4A6A, MZB1, P2RY14, 
          PADI4, PAX5, PLA2G16, PLAC8, PLVAP, PNOC, POU2AF1, PRSS33, PTGS1, RNASE2, RPS6KA4, SLC35F3, SLC38A5, SMPD3, SPIB, STAB1, STARD5, TBC1D4, 
          TCL1A, TMEM176B, TNFRSF13B, TRPM2]
